<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="google.test"
    errors="1" failures="0" hostname="" id="" package="google.test" skipped="0"
    tests="1" time="0.008000" timestamp="Sat, 24 Mar 2018 15:02:25 GMT">
  
    <testcase name="Demo test Google" classname="google.test" time="0.008000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Google Test / Demo test Google]:

  ReferenceError: AwesomeTable is not defined
    at Object.Demo test Google (/Users/embrasse-moi/Documents/Code/awesome-table/nightwatch/google.test.js:16:21)
    at Module.call (/Users/embrasse-moi/Documents/Code/awesome-table/node_modules/nightwatch/lib/runner/module.js:62:34)
    at /Users/embrasse-moi/Documents/Code/awesome-table/node_modules/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/Users/embrasse-moi/Documents/Code/awesome-table/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/embrasse-moi/Documents/Code/awesome-table/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/embrasse-moi/Documents/Code/awesome-table/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /Users/embrasse-moi/Documents/Code/awesome-table/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/Users/embrasse-moi/Documents/Code/awesome-table/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/Users/embrasse-moi/Documents/Code/awesome-table/node_modules/nightwatch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
